export const BASE_URL = "http://localhost:8099/api/v1.0"
export const DEF_BASEURL = 'http://localhost:8099'
export const ADMIN_TYPE = 1
export const USER_TYPE = 2
export const ADMIN_USER = '管理员'
export const GENERAL_USER = '用 户'
export const ADD_TITLE = '新 增'
export const EDIT_TITLE = '编 辑'
export const DELETE_TITLE = '删 除'
export const CHP_DEVICE = '充电桩'
export const ENV_DEVICE = '环境舱'
export const ON_LINE = '在 线'
export const OFF_LINE = '离 线'
export const SEARCH_CONDITION = '请输入查询条件！'
export const SEARCH_SUCCESS = '查询完成！'
export const SEARCH_FAIL = '查询失败！'
export const ADD_USER_SUCCESS = '已新增用户！'
export const ADD_USER_FAIL = '新增用户失败！'
export const EDIT_USER_SUCCESS = '已编辑！'
